Reframe the InCommon host cert options
jteheran/docs pull request #1
Opened 2019-04-25 21:30 UTC by brianhlin

I'd like the documentation to focus on use cases instead of tools. Plus some other misc focuses.

Once we get this PR approved and merged, I'll approve and merge: https://github.com/opensciencegrid/docs/pull/537

2019-05-07 17:31 UTC, brianhlin commented
@jteheran can you review and merge this?

2019-05-08 14:49 UTC, jteheran commented on docs/security/host-certs.md
> +1. Request a Department Registration Authority user with SSL auto-approve enabled and client certificate:
Request a Department Registration Authority user with SSL auto-approve enabled and a client certificate:

2019-05-08 14:50 UTC, jteheran commented on docs/security/host-certs.md
> +    - If they grant your request, you will receive an email with your client certificate.
If they grant your request, you will receive an email with instructions on how to request your client certificate.

2019-05-08 14:51 UTC, jteheran commented on docs/security/host-certs.md
>          user@host $ osg-incommoncert-request --username <INCOMMONLOGIN> \
user@host $ osg-incommoncert-request --username **<INCOMMON_LOGIN>**

2019-05-08 14:51 UTC, jteheran requested changes
I left three comments.

2019-05-08 15:28 UTC, brianhlin commented
@jteheran alright, comments should be addressed. Just an FYI for the future, you can add "suggestions" to the PR so that the author can accept them directly via the GitHub interface (https://help.github.com/en/articles/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request)

2019-05-08 15:41 UTC, jteheran commented
That's what I thought I did. I added line comments. Not sure what went wrong.

2019-05-08 16:16 UTC, brianhlin commented
When you're adding an in-line comment, there's a button in the UI that turns it into a suggestion, which should add something that looks like the following to the text box:

    ```suggestion
    <original text here>
    ```
Does the PR look good now? Can you merge it?

2019-05-08 16:16 UTC, merged